config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users,skip: [:passwords], controllers: {
  registrations: "end_user/registrations",
  sessions: 'end_user/sessions'
}



 scope module: :end_user do
   post '/guests/guest_sign_in', to: 'guests#new_guest'
   root to:'homes#top'
   get "/homes" => "homes#top"
   resources :end_users, only:[:index, :show, :edit, :update] do
     member do
      get :favorites
     end
   end
   #get "/end_users/favorites" => "end_users#favorites"
   resources :submissions do
     resources :comments,    only:[:create, :destroy]
     resource :favorites,    only:[:create, :destroy]
   end
   get "search" => "searches#search"
 end

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
 get "homes" => "homes#top"
 resources :end_users,   only:[:index, :show, :edit, :update]
 resources :submissions, only:[:index, :show, :destroy] do
  resources :comments,    only:[:destroy]
 end
end

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :submissions, dependent: :destroy
  has_many :comments,    dependent: :destroy
  has_many :favorites,   dependent: :destroy

   validates :name, uniqueness: true, length: {in: 2..20}
   validates :introduction, length: {maximum:50}

  def get_profile_image
   unless profile_image.attached?
     file_path = Rails.root.join('app/assets/images/no_image.jpg')
     profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
  profile_image.variant(resize_to_limit: [100, 100]).processed
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @end_user = EndUser.where("name LIKE?", "#{word}")

    elsif search == "forward_match"
      @end_user = EndUser.where("name LIKE?","#{word}%")

    elsif search == "backward_match"
      @end_user = EndUser.where("name LIKE?","%#{word}")

    elsif search == "partial_match"
      @end_user = EndUser.where("name LIKE?","%#{word}%")

    else
      @end_user = EndUser.all
    end
  end
end

app/models/submission.rb
class Submission < ApplicationRecord

  has_one_attached :image
  belongs_to :end_user
  has_many :comments,        dependent: :destroy
  has_many :favorites,       dependent: :destroy
  has_many :submission_tags, dependent: :destroy
  has_many :tags,            through: :submission_tags
  
   def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
   end

  def favorited_by?(end_user)
    favorites.exists?(end_user_id: end_user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @submission = Submission.where("body LIKE?","#{word}")

    elsif search == "forward_match"
      @submission = Submission.where("body LIKE?","#{word}%")

    elsif search == "backward_match"
      @submission = Submission.where("body LIKE?","%#{word}")

    elsif search == "partial_match"
      @submission = Submission.where("body LIKE?","%#{word}%")

    else
      @submission = Submission.all
    end
  end
end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
  before_action :authenticate_admin!
  def index
     @end_users = EndUser.all
  end

  def show
    @end_user = EndUser.find(params[:id])
    @submissions = @end_user.submissions
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    @end_user = EndUser.find(params[:id])
    @end_user.update(end_user_params)
    redirect_to admin_end_user_path(@end_user.id)
  end

  private

  def end_user_params
   params.require(:end_user).permit(:id, :name, :introduction, :is_deleted)
  end
end

app/controllers/admin/submissions_controller.rb
class Admin::SubmissionsController < ApplicationController
 before_action :authenticate_admin!

 def index
   @submissions = Submission.all
 end

 def show
   @submission = Submission.find(params[:id])
   @end_user = @submission.end_user
 end

 def destroy
   @submission = Submission.find(params[:id])
   @submission.destroy
   redirect_to admin_submissions_path
 end

end

app/controllers/end_user/comments_controller.rb
class EndUser::CommentsController < ApplicationController
  def create
    @submission = Submission.find(params[:submission_id])
    @comment = current_end_user.comments.new(comment_params)
    @comment.submission_id = @submission.id
    @comment.save
    redirect_to submission_path(@submission.id)
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to submission_path(params[:submission_id])
  end
  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/end_user/confirmations_controller.rb
# frozen_string_literal: true

class EndUser::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/end_user/end_users_controller.rb
class EndUser::EndUsersController < ApplicationController

  def index
    @end_users = EndUser.all
    @end_user = current_end_user
    @submission = Submission.new
  end

  def show
    @end_user = EndUser.find(params[:id])
    @submissions = @end_user.submissions
    @submission = Submission.new
  end

  def edit
    @end_user = EndUser.find(params[:id])
    if @end_user == current_end_user
      render "edit"
    else
      redirect_to end_user_path(current_end_user)
    end
  end

  def update
    @end_user = EndUser.find(params[:id])
    if @end_user.update(end_user_params)
    redirect_to end_user_path(@end_user.id)
    else
     render :edit
    end
  end

  def favorites
    @end_user = EndUser.find_by(id: params[:id])
    @favorites = Favorite.where(end_user: @end_user.id)
  end

  private

  def end_user_params
    params.require(:end_user).permit(:name, :profile_image, :introduction)
  end
end

app/controllers/end_user/favorites_controller.rb
class EndUser::FavoritesController < ApplicationController

  def create
    @submission = Submission.find(params[:submission_id])
    @favorite = current_end_user.favorites.new(submission_id: @submission.id)
    @favorite.save
    redirect_to submission_path(@submission)
  end

  def destroy
    @submission = Submission.find(params[:submission_id])
    @favorite = current_end_user.favorites.find_by(submission_id: @submission.id)
    @favorite.destroy
    redirect_to submission_path(@submission)
  end
end

app/controllers/end_user/guests_controller.rb
class EndUser::GuestsController < ApplicationController

  def new_guest
   end_user = EndUser.find_or_create_by!(email: 'guest@example.com') do |end_user|
     end_user.password = SecureRandom.urlsafe_base64
     end_user.name = "ゲストユーザー"
     end_user.introduction = "お試しログインです"
     # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
   end
   sign_in end_user
   redirect_to submissions_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/end_user/homes_controller.rb
class EndUser::HomesController < ApplicationController

  def top
  end

end

app/controllers/end_user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class EndUser::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/end_user/passwords_controller.rb
# frozen_string_literal: true

class EndUser::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/end_user/registrations_controller.rb
# frozen_string_literal: true

class EndUser::RegistrationsController < Devise::RegistrationsController
   before_action :check_guest, only: :destroy
   def check_guest
     if resource.email == 'guest@example.com'
       redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
     end
   end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_user/searches_controller.rb
class EndUser::SearchesController < ApplicationController
    before_action :authenticate_end_user!

  def search
    @range = params[:range]

    if @range == "EndUser"
      @end_users = EndUser.looks(params[:search], params[:word])
      render "end_user/end_users/index"
    else
      @submissions = Submission.looks(params[:search], params[:word])
      render "end_user/submissions/index"
    end
  end
end

app/controllers/end_user/sessions_controller.rb
# frozen_string_literal: true

class EndUser::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
    before_action :end_user_state, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
 def end_user_state
  ## 【処理内容1】 入力されたemailからアカウントを1件取得
  @end_user = EndUser.find_by(email: params[:end_user][:email])
  ## アカウントを取得できなかった場合、このメソッドを終了する
  return if !@end_user
  ## 【処理内容2】 取得したアカウントのパスワードと入力されたパスワードが一致してるかを判別
  if @end_user.valid_password?(params[:end_user][:password]) && (@end_user.is_deleted == true)
    ## 【処理内容3】
   redirect_to new_end_user_registration_path
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
 end
end

app/controllers/end_user/submission_tags_controller.rb
class EndUser::SubmissionTagsController < ApplicationController

 
end

app/controllers/end_user/submissions_controller.rb
class EndUser::SubmissionsController < ApplicationController

  def index
    @submission = Submission.new
    @submissions = Submission.all

    @submissions = params[:tag_id].present? ? Tag.find(params[:tag_id]).submissions : Submission.all
  end

  def show
    @submission = Submission.find(params[:id])
    @end_user = @submission.end_user
    @newsubmission = Submission.new
    @newsubmission.submission_tags.build
    @comment = Comment.new
  end

  def new
    @submission = Submission.new
  end

  def create
    tag_ids = params.dig(:submission, :submission_tags, :tag_ids).compact_blank
    @submission = current_end_user.submissions.build(submission_params)
    tag_ids.each do |tag_id|
      @submission.submission_tags.build(tag_id: tag_id)
    end
    
    if @submission.save
    redirect_to submission_path(@submission)
    else
      @submissions = Submission.all
      @end_user = current_end_user.id
      render :index
    end
  end

  def edit
    @submission = Submission.find(params[:id])
    if @submission.end_user == current_end_user
     render "edit"
    else
     redirect_to submissions_path
    end
  end

  def update
    @submission = Submission.find(params[:id])
    if @submission.update(submission_params)
     redirect_to submission_path(@submission.id)
    else
     render :edit
    end
  end

  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy
    redirect_to submissions_path
  end

  private

  def submission_params
    params.require(:submission).permit(:body, :image)
  end
end

app/controllers/end_user/tags_controller.rb
class EndUser::TagsController < ApplicationController
end

app/controllers/end_user/unlocks_controller.rb
# frozen_string_literal: true

class EndUser::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/end_user_helper.rb
module Admin::EndUserHelper
end

app/views/end_user/submissions/_form.html.erb
    <h2>プロフィール</h2>

       <%= image_tag end_user.get_profile_image %>

      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
           <th>ユーザー名</th>
           <th><%= end_user.name %></th>
          </tr>
          <tr>
            <th>自己紹介</th>
            <th><%= end_user.introduction %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">
          <%= link_to "プロフィール編集", edit_end_user_path(end_user.id), class: "btn btn-outline-secondary btn-block" %>

      </div>

  <h2 class="mt-3">新規投稿</h2>
  <%= form_with model: submission do |f| %>

  <label for="image">画像選択</label></br>
  <%= f.file_field :image, accept: "image/*" %></br>

  <label for="opinion">本文</label></br>
  <%= f.text_area :body %></br>

 <label for="tag">タグ</label></br>
  <%= f.fields_for :submission_tags do |ff| %>
     <%= ff.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
  <% end %></br>


  <%= f.submit '投稿', class:"btn btn-success btn-sm" %>

  <% end %>

app/views/end_user/submissions/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>投稿編集</h1>

      <%= form_with model: @submission do |f| %>



      <div class="form-group">

        <label for="inputImage">画像</label>
        <%= f.file_field :image, accept: "image/*" %>

        <label for="inputBody">本文</label></br>
        <%= f.text_area :body, id:"inputBody" %>
      </div>

      <%= f.submit "変更内容を保存する", class:"btn btn-success btn-sm" %>
      <% end %>

      <a class="book_show">
        <%= link_to "戻る", submission_path(@submission.id) %>
      </a>
      |
      <a class="back">
        <%= link_to "一覧に戻る", submissions_path %>
      </a>


    </div>
  </div>
</div>

app/views/end_user/submissions/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
 <div class='row'>
  <div class="col-md-3">
  <%= render 'end_user/submissions/form', submission: @submission, end_user: current_end_user %>
  </div>

  <div class="col-md-8 offset-md-1">
  <h2>投稿一覧</h2>
    <%= form_tag submissions_path, method: :get, class: 'boards__searchForm' do %>
      <%= select_tag :tag_id,
                     options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                     {
                       prompt: 'タグで絞り込み検索',
                       onchange: 'submit(this.form);'
                     }
      %>
    <% end %>
  <table class="table table-hover table-inverse">

    <tbody>
     <% @submissions.each do |submission| %>
     <tr>
      <td>
        <%= link_to submission_path(submission.id) do %>
         <%= image_tag submission.get_image(100, 100) %>
        <% end %>

        <%= link_to submission.end_user.name, end_user_path(submission.end_user) %>
      </td>
      <td><%= submission.body %></td>

      <td>
        <% submission.tags.each do |tag| %>
         <%= tag.name %>
        <% end %>
      </td>

     </tr>
     <% end %>
    </tbody>

  </table>
  </div>
 </div>
</div>

app/views/end_user/submissions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
     <%= render 'form', submission: @newsubmission, end_user: @end_user %>
    </div>
     <div class="col-md-8 offset-md-1">
       <h2>投稿詳細</h2>
       <table class="table">
         <tbody>
           <tr>
             <td>
               <%= image_tag @submission.get_image(200, 200) %>
             </td>
           </tr>

             <tr>
             <td>
               <%= link_to @end_user.name, end_user_path(@end_user) %>
            </td>
            </tr>

            <tr>
             <td><%= @submission.body %></td>
            </tr>

            <tr>
             <td>
              <% @submission.tags.each do |tag| %>
               <%= tag.name %>
              <% end %>
             </td>
            </tr>

             <tr>
             <td>
              <% if @submission.end_user == current_end_user %>
              <%= link_to "投稿を編集", edit_submission_path(@submission.id), class:"btn btn-success btn-sm" %>
              <% end %>
             </td>
             <td>
              <% if @submission.end_user == current_end_user %>
               <%= link_to "投稿を削除", submission_path(@submission.id), class:"btn btn-danger btn-sm", method: :delete, "data-confirm" => "本当に消しますか？" %>
              <% end %>
             </td>
           </tr>
         </tbody>
       </table>

       <div>
        <% if @submission.favorited_by?(current_end_user) %>
          <p>
            <%= link_to submission_favorites_path(@submission), method: :delete do %>
              ♥<%= @submission.favorites.count %> いいね
            <% end %>
          </p>
          <% else %>
          <p>
            <%= link_to submission_favorites_path(@submission), method: :post do %>
              ♡<%= @submission.favorites.count %> いいね
            <% end %>
          </p>
        <% end %>
       </div>

       <div>
       <%= form_with model: [@submission, @comment] do |f| %>
        <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
        <%= f.submit "送信する", class:"btn btn-success btn-sm" %>
       <% end %>
       </div>

       <div>
        <p>コメント件数：<%= @submission.comments.count %></p>

        <table class="table table-hover table-inverse">
         <tbody>
          <% @submission.comments.each do |comment| %>
          <tr>
           <td><%= link_to comment.end_user.name, end_user_path(@end_user) %></td>
           <td><%= comment.created_at.strftime('%Y/%m/%d') %></td>
           <td><%= comment.comment %></td>
           <td>
             <% if comment.end_user == current_end_user %>
              <%= link_to "削除", submission_comment_path(comment.submission, comment), method: :delete %>
             <% end %>
            </td>
          </tr>
          <% end %>
         </table>
        </div>
       </div>
     </div>
  </div>
</div>