config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users,skip: [:passwords], controllers: {
  registrations: "end_user/registrations",
  sessions: 'end_user/sessions'
}



 scope module: :end_user do
   post '/guests/guest_sign_in', to: 'guests#new_guest'
   root to:'homes#top'
   get "/homes" => "homes#top"
   resources :end_users, only:[:index, :show, :edit, :update] do
     member do
      get :favorites
     end
   end
   #get "/end_users/favorites" => "end_users#favorites"
   resources :submissions do
     resources :comments,    only:[:create, :destroy]
     resource :favorites,    only:[:create, :destroy]
   end
   get "search" => "searches#search"
 end

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
 get "homes" => "homes#top"
 resources :end_users,   only:[:index, :show, :edit, :update]
 resources :submissions, only:[:index, :show, :destroy] do
  resources :comments,    only:[:destroy]
 end
end

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :end_user
  belongs_to :submission
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :submissions, dependent: :destroy
  has_many :comments,    dependent: :destroy
  has_many :favorites,   dependent: :destroy

   validates :name, uniqueness: true, length: {in: 2..20}
   validates :introduction, length: {maximum:50}

  def get_profile_image
   unless profile_image.attached?
     file_path = Rails.root.join('app/assets/images/no_image.jpg')
     profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
  profile_image.variant(resize_to_limit: [100, 100]).processed
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @end_user = EndUser.where("name LIKE?", "#{word}")

    elsif search == "forward_match"
      @end_user = EndUser.where("name LIKE?","#{word}%")

    elsif search == "backward_match"
      @end_user = EndUser.where("name LIKE?","%#{word}")

    elsif search == "partial_match"
      @end_user = EndUser.where("name LIKE?","%#{word}%")

    else
      @end_user = EndUser.all
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :end_user
  belongs_to :submission
end

app/models/submission.rb
class Submission < ApplicationRecord

  has_one_attached :image
  belongs_to :end_user
  has_many :comments,        dependent: :destroy
  has_many :favorites,       dependent: :destroy
  has_many :submission_tags, dependent: :destroy
  has_many :tags,            through: :submission_tags
  
   def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
   end

  def favorited_by?(end_user)
    favorites.exists?(end_user_id: end_user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @submission = Submission.where("body LIKE?","#{word}")

    elsif search == "forward_match"
      @submission = Submission.where("body LIKE?","#{word}%")

    elsif search == "backward_match"
      @submission = Submission.where("body LIKE?","%#{word}")

    elsif search == "partial_match"
      @submission = Submission.where("body LIKE?","%#{word}%")

    else
      @submission = Submission.all
    end
  end
end

app/models/submission_tag.rb
class SubmissionTag < ApplicationRecord
  attribute :tag_ids
  belongs_to :submission
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :submission_tags, dependent: :destroy
  has_many :submissions, through: :submission_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

 def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_submissions_path
    else
        submissions_path
    end
 end

 def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :end_user
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
 end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/end_user_helper.rb
module Admin::EndUserHelper
end

app/helpers/admin/guests_helper.rb
module Admin::GuestsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/submissions_helper.rb
module Admin::SubmissionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/end_user/guests_helper.rb
module EndUser::GuestsHelper
end

app/helpers/end_user/homes_helper.rb
module EndUser::HomesHelper
end

app/helpers/end_user/tags_helper.rb
module EndUser::TagsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VListenerComu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>
  <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Vコミュ</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
             <% if end_user_signed_in? %>

             <%= link_to  "マイページ", end_user_path(current_end_user), class:"btn btn-outline-primary nav-link text-light" %>

             <%= link_to "投稿一覧", submissions_path, class:"btn btn-outline-primary nav-link text-light" %>

             <%= link_to "ユーザー一覧", end_users_path, class:"btn btn-outline-primary nav-link text-light" %>

             <%= link_to "ログアウト", destroy_end_user_session_path, method: :delete,  class:"btn btn-outline-primary nav-link text-light" %>

              <div class="search_form">
                <%= form_with url: search_path, local: true, method: :get do |f| %>
                  <%= f.text_field :word %>
                  <%= f.select :range, options_for_select([['EndUser'], ['Submission']]) %>
                  <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
                  <%= f.submit "検索", class: "btn btn-primary" %>
                <% end %>
              </div>

             <% elsif admin_signed_in? %>

             <%= link_to "投稿一覧", admin_submissions_path, class:"btn btn-outline-primary nav-link text-light" %>

             <%=link_to "ユーザー一覧", admin_end_users_path, class:"btn btn-outline-primary nav-link text-light" %>

             <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"btn btn-outline-primary nav-link text-light" %>


              <% else %>

              <%= link_to "ホーム", root_path, class:"btn btn-outline-primary nav-link text-light" %>

              <%= link_to "新規登録", new_end_user_registration_path, class:"btn btn-outline-primary nav-link text-light" %>

              <%= link_to "ログイン", new_end_user_session_path, class:"btn btn-outline-primary nav-link text-light" %>

              <% end %>

        </ul>
      </div>
    </div>
  </nav>
</header>


    <main>
     <%= yield %>
    </main>

    <footer>
     <div class='container mt-5'>
  	   <div class='row'>
    	   <div class='mx-auto'>
    	    	<p></p>
       	 </div>
       </div>
     </div>
    </footer>
  </body>
</html>