config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users,skip: [:passwords], controllers: {
  registrations: "end_user/registrations",
  sessions: 'end_user/sessions'
}



 scope module: :end_user do
   post '/guests/guest_sign_in', to: 'guests#new_guest'
   root to:'homes#top'
   get "/homes" => "homes#top"
   resources :end_users, only:[:index, :show, :edit, :update] do
     member do
      get :favorites
     end
   end
   #get "/end_users/favorites" => "end_users#favorites"
   resources :submissions do
     resources :comments,    only:[:create, :destroy]
     resource :favorites,    only:[:create, :destroy]
   end
   get "search" => "searches#search"
 end

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
 get "homes" => "homes#top"
 resources :end_users,   only:[:index, :show, :edit, :update]
 resources :submissions, only:[:index, :show, :destroy] do
  resources :comments,    only:[:destroy]
 end
end

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :end_user
  belongs_to :submission
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :submissions, dependent: :destroy
  has_many :comments,    dependent: :destroy
  has_many :favorites,   dependent: :destroy

   validates :name, uniqueness: true, length: {in: 2..20}
   validates :introduction, length: {maximum:50}

  def get_profile_image
   unless profile_image.attached?
     file_path = Rails.root.join('app/assets/images/no_image.jpg')
     profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
  profile_image.variant(resize_to_limit: [100, 100]).processed
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @end_user = EndUser.where("name LIKE?", "#{word}")

    elsif search == "forward_match"
      @end_user = EndUser.where("name LIKE?","#{word}%")

    elsif search == "backward_match"
      @end_user = EndUser.where("name LIKE?","%#{word}")

    elsif search == "partial_match"
      @end_user = EndUser.where("name LIKE?","%#{word}%")

    else
      @end_user = EndUser.all
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :end_user
  belongs_to :submission
end

app/models/submission.rb
class Submission < ApplicationRecord

  has_one_attached :image
  belongs_to :end_user
  has_many :comments,        dependent: :destroy
  has_many :favorites,       dependent: :destroy
  has_many :submission_tags, dependent: :destroy
  has_many :tags,            through: :submission_tags
  
   def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
   end

  def favorited_by?(end_user)
    favorites.exists?(end_user_id: end_user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @submission = Submission.where("body LIKE?","#{word}")

    elsif search == "forward_match"
      @submission = Submission.where("body LIKE?","#{word}%")

    elsif search == "backward_match"
      @submission = Submission.where("body LIKE?","%#{word}")

    elsif search == "partial_match"
      @submission = Submission.where("body LIKE?","%#{word}%")

    else
      @submission = Submission.all
    end
  end
end

app/models/submission_tag.rb
class SubmissionTag < ApplicationRecord
  attribute :tag_ids
  belongs_to :submission
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :submission_tags, dependent: :destroy
  has_many :submissions, through: :submission_tags
end

app/controllers/admin/submissions_controller.rb
class Admin::SubmissionsController < ApplicationController
 before_action :authenticate_admin!

 def index
   @submissions = Submission.all
 end

 def show
   @submission = Submission.find(params[:id])
   @end_user = @submission.end_user
 end

 def destroy
   @submission = Submission.find(params[:id])
   @submission.destroy
   redirect_to admin_submissions_path
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

 def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_submissions_path
    else
        submissions_path
    end
 end

 def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :end_user
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
 end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/end_user/submissions_controller.rb
class EndUser::SubmissionsController < ApplicationController

  def index
    @submission = Submission.new
    @submissions = Submission.all

    @submissions = params[:tag_id].present? ? Tag.find(params[:tag_id]).submissions : Submission.all
  end

  def show
    @submission = Submission.find(params[:id])
    @end_user = @submission.end_user
    @newsubmission = Submission.new
    @newsubmission.submission_tags.build
    @comment = Comment.new
  end

  def new
    @submission = Submission.new
  end

  def create
    tag_ids = params.dig(:submission, :submission_tags, :tag_ids).compact_blank
    @submission = current_end_user.submissions.build(submission_params)
    tag_ids.each do |tag_id|
      @submission.submission_tags.build(tag_id: tag_id)
    end
    
    if @submission.save
    redirect_to submission_path(@submission)
    else
      @submissions = Submission.all
      @end_user = current_end_user.id
      render :index
    end
  end

  def edit
    @submission = Submission.find(params[:id])
    if @submission.end_user == current_end_user
     render "edit"
    else
     redirect_to submissions_path
    end
  end

  def update
    @submission = Submission.find(params[:id])
    if @submission.update(submission_params)
     redirect_to submission_path(@submission.id)
    else
     render :edit
    end
  end

  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy
    redirect_to submissions_path
  end

  private

  def submission_params
    params.require(:submission).permit(:body, :image)
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/end_user_helper.rb
module Admin::EndUserHelper
end

app/helpers/admin/guests_helper.rb
module Admin::GuestsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/submissions_helper.rb
module Admin::SubmissionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/end_user/comments_helper.rb
module EndUser::CommentsHelper
end

app/helpers/end_user/guests_helper.rb
module EndUser::GuestsHelper
end

app/helpers/end_user/homes_helper.rb
module EndUser::HomesHelper
end

app/helpers/end_user/searches_helper.rb
module EndUser::SearchesHelper
end

app/helpers/end_user/submissions_helper.rb
module EndUser::SubmissionsHelper
end

app/helpers/end_user/tags_helper.rb
module EndUser::TagsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/submissions/index.html.erb
<div class="container px-5 px-sm-0">
 <div class='row'>
  <div class="col-md-10 offset-md-1">
   <h2>投稿一覧</h2>
    <table class="table table-hover table-inverse">

    <thead>
      <tr>
        <th>投稿画像</th>
        <th>ユーザー名</th>
        <th>投稿文</th>
        <th>タグ</th>
      </tr>
    </thead>

    <tbody>
     <% @submissions.each do |submission| %>
     <tr>
      <td>
        <%= link_to admin_submission_path(submission.id) do %>
         <%= image_tag submission.get_image(100, 100) %>
        <% end %>
      </td>

      <td>
        <%= link_to submission.end_user.name, admin_end_user_path(submission.end_user) %>
      </td>

      <td><%= submission.body %></td>

      <td>
        <% submission.tags.each do |tag| %>
         <%= tag.name %>
        <% end %>
      </td>

     </tr>
     <% end %>
    </tbody>

  </table>
  </div>
 </div>
</div>

app/views/admin/submissions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1">
       <h2>投稿詳細</h2>
       <table class="table">
         <tbody>
           <tr>
             <td>
               <%= image_tag @submission.get_image(200, 200) %>
             </td>
           </tr>

             <tr>
             <td>
               <%= link_to @end_user.name, admin_end_user_path(@end_user) %>
            </td>
            </tr>

            <tr>
             <td><%= @submission.body %></td>
            </tr>

            <tr>
             <td>
              <% @submission.tags.each do |tag| %>
               <%= tag.name %>
              <% end %>
             </td>
            </tr>

            <tr>
              <%= link_to "投稿を削除", admin_submission_path(@submission.id), class:"btn btn-danger btn-sm", method: :delete, "data-confirm" => "本当に消しますか？" %>
            </tr>
         </tbody>
       </table>
              <div>
        <p>コメント件数：<%= @submission.comments.count %></p>

        <table class="table table-hover table-inverse">
         <tbody>
          <% @submission.comments.each do |comment| %>
          <tr>
           <td><%= link_to comment.end_user.name, admin_end_user_path(@end_user) %></td>
           <td><%= comment.created_at.strftime('%Y/%m/%d') %></td>
           <td><%= comment.comment %></td>
           <td><%= link_to "削除", admin_submission_comment_path(comment.submission, comment), class:"btn btn-danger btn-sm", method: :delete, "data-confirm" => "本当に消しますか？" %></td>
          </tr>
          <% end %>
         </table>
   </div>
  </div>
</div>
</div>